version: 0.0
os: linux

files:
  source: /
  destination: /home/ubuntu/server

hooks:

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
